### ISSUE TITLE
Doesn't deploy on heroku anymore

### ISSUE THREAD

**Issue by mike347** [tkrajcar/github-notify-mush#2]
Heroku doesn't support the version of Ruby Heroku wants anymore, so it fails to deploy.
if I update the files to a newer version of Ruby (e.g. 2.5.1) it complains of problems with Sinatra.
I'm not familiar enough with Ruby/etc to fix it myself, so opening an issue. :)

**Comment by tkrajcar** [comment]
Thanks for letting me know. Fixed in 83793462e33ab25a52a4c920383ed4a1f9e926a9
